/**
 * @file
 * Code generated by: http://www.updatemybrowser.org/widget.
 */

/**
 * Add behaviour for advance settings.
 */
(function($) {
  Drupal.behaviors.umb_settings = {
    attach: function(context, settings) {
      
    }
  };
})(jQuery);

(function() {
  var s = document.createElement('script'); s.type = 'text/javascript'; s.async = true;
  s.src = ('https:' == document.location.protocol?'https://':'http://') + 'updatemybrowser.org/umb.js';
  var b = document.getElementsByTagName('script')[0]; b.parentNode.insertBefore(s, b);
})();
